### ISSUE TITLE
Toastをリッチにする

### ISSUE THREAD

**Issue by tetsuya2223** [tetsuya2223/nextjs-pages-todo-app#60]
・タスク削除完了時にも表示
・アニメーションをつける

**Comment by kimuniiii** [comment]
今回はコンポーネントが unMount されるときにも
アニメーションを付与してほしいのでそこ頑張ってね！

**Comment by kimuniiii** [comment]
普通にCSSを当てるだけだと
コンポーネントがアンマウントされるときに
アニメーションが効かないので！！

**Comment by tetsuya2223** [comment]
アンマウント時にアニメーションが効かない理由は、アンマウントされると瞬時に（アニメーションが完了する前に）画面から消えるから。
ではどうするのか？アニメーションが完了してからアンマウントするようにしたら良い。
どうやって？

**Comment by tetsuya2223** [comment]
一旦ここまで記述してみて、「これ`isFadingOut`もcontextで管理する必要あるな。めんどくさいな」となりました。
```tsx
//非表示よりも先にfadeoutの状態を更新
  //マウントしたら3秒後にfadeoutアニメーションが開始

  useEffect(() => {
    if (!isFadingOut) return;

    const timer = setTimeout(() => {
      setIsFadingOut(true);
    }, 3000);

    return () => clearTimeout(timer);
  }, []);

  //IsFadingOutが完了するまで待機
  useEffect(() => {
    if (isFadingOut) {
      const timer = setTimeout(() => {
        setIsToastOpen(false);
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [isFadingOut]);
```

**Comment by kimuniiii** [comment]
これは useAnimationUnmount という custom hooks を作成すればいい感じにできるんだよね。ちょっと待ってな。飯食った後に第一ヒントを出す！！

**Comment by tetsuya2223** [comment]
お願いいたします！

**Comment by kimuniiii** [comment]
そしてこの Hooks を使用して
スタイルを以下のように分岐する！

```css
animation-name: isVisible ? slideStart("-50%", "240px", "-50%", "0") : slideEnd("-50%", "0", "-50%", "240px")};
```

**Comment by tetsuya2223** [comment]
上記のhooksの記述で、isVisibleはいつfalseになる（toastが非表示になる）んですかね？
toastの非表示の管理は、toast.tsxでする感じですかね？

**Comment by tetsuya2223** [comment]
```tsx
export const Toast: React.FC = () => {
  const { isToastOpen, toastType } = useToastContext();
  const { display } = useFade(isToastOpen, 250);

  if (!display) return null;

  useEffect(() => {
    if (!display) return;

    //displayをfalseにしたい
    const timer = setTimeout(() => {}, 3000);
  }, []);

  return (
    <div className={toastStyles.toastContainer}>
      <div className={`${toastStyles.toast} ${toastStyles[toastType]}}`}>
        {toastType === "success" ? "成功しました！" : "エラーが発生しました"}
      </div>
    </div>
  );
};

```

**Comment by kimuniiii** [comment]
そう！あってる！

Toastコンポーネント内で
表示・非表示を useFade を
使用して切り替えるようにする！

useFade の引数に
context で管理している
表示・非表示フラグを渡せば良い！

**Comment by tetsuya2223** [comment]
ありがとうございます！
```tsx
export const Toast: React.FC = () => {
  const { isToastOpen, toastType } = useToastContext();
  const { display } = useFade(isToastOpen, 250);

  if (!display) return null;

  // displayをfalseにしたい
  // useEffect(() => {
  //   if (!display) return;

  //   const timer = setTimeout(() => {}, 3000);
  // }, []);

  return (
    <div className={toastStyles.toastContainer}>
      <div className={`${toastStyles.toast} ${toastStyles[toastType]}}`}>
        {toastType === "success" ? "成功しました！" : "エラーが発生しました"}
      </div>
    </div>
  );
};
```

` const { display } = useFade(isToastOpen, 250);`このようにToastコンポーネントでuseFadeを使用しようとしているのですが、
これだけだと`isVisible`がfalseに切り替わらないので、useEffectでfalseに切り替えるっていう認識であってますか？

**Comment by kimuniiii** [comment]
> これだけだとisVisibleがfalseに切り替わらないので、useEffectでfalseに切り替えるっていう認識であってますか？

お、まじ??

useFade の useEffect
の内部処理は実行されない??

**Comment by tetsuya2223** [comment]
```tsx
useEffect(() => {
    /** 表示時の処理 */
    if (isVisible) {
      setDisplay(isVisible); ⇒これを setDispley(false)に変更
      return;
    }
```

**Comment by kimuniiii** [comment]
いや、嘘ついたわ。山岸があってるわ。

**Comment by kimuniiii** [comment]
## Toast コンポーネント

```tsx
export const Toast: FC<ToastProps> = (props) => {
  const { isToastVisible, toastText, toastType, closeToast } = props;

  const { display } = useFade(isToastVisible);

  /** 3秒後に`Toast`は自動的に消えるようにするイベントハンドラ */
  const handleHideToast = () => {
    timerId = window.setTimeout(() => closeToast(), 3000);
    return () => clearTimeout(timerId);
  };

  useEffect(handleHideToast, [isToastVisible]);

  if (!display) return null;

  return <div>Toast</div>
};
```

**Comment by kimuniiii** [comment]
うん。そうだな。山岸が合ってるわ。

**Comment by tetsuya2223** [comment]
`closeToast()`と言うtoastを閉じる用のcontextを追加。
それをtoastコンポーネント内で使用。って感じですかね！
やってみます！ありがとうございます！

**Comment by kimuniiii** [comment]
> closeToast() と言う toastを閉じる用のcontextを追加。
それをtoastコンポーネント内で使用。って感じですかね！
やってみます！ありがとうございます！

YES！合ってる！よろしく！がんばれ！努力！

**Comment by tetsuya2223** [comment]
```tsx
return (
    <div className={toastStyles.toastContainer}>
      <div
        className={`${toastStyles.toast} ${toastStyles[toastType]}
        ${display ? toastStyles.show : ""} 
        ${isFadingOut ? toastStyles.hidden : ""} 
        `}
      >
        {toastType === "success" ? "成功しました！" : "エラーが発生しました"}
      </div>
    </div>
```

```css
.toast {
  position: fixed;
  bottom: 100px;
  left: 50%;
  transform: translateX(-50%) translateY(100px);
  padding: 16px;
  background-color: #333;
  color: #fff;
  border-radius: 4px;
  opacity: 1;
  visibility: hidden;
  transition: opacity 250ms ease-out, transform 250ms ease-out;
}

.toast.show {
  opacity: 1;
  transform: translateX(-50%) translateY(0px);
  visibility: visible;
}
.toast.hidden {
  opacity: 0;
  transform: translateX(-50%) translateY(100px);
}
```

**Comment by tetsuya2223** [comment]
アンマウント時のアニメーションは実装できたのですが、今度は出現時のアニメーションが効かなくなりました・・

・初回出現時はアニメーションが効かずその場から出現
⇒アンマウント時はアニメーションが効き画面下部へ移動しながら消失
⇒次のマウント時はアニメーションが効き下から出現
と言う感じに初回だけアニメーションがうまく行きません。

原因わかりますか・・？

**Comment by tetsuya2223** [comment]
元々、マウント時のアニメーションは下記の様に記述してましたが、アンマウント時のアニメーションも追加する際に、keyFrmaesがあると変な挙動のなったので、transform,transionで実装するように変更しました。そしたら初回マウント時のアニメーションが効かなくなりました。
```css
@keyframes toastIn {
  0% {
    opacity: 0;
    transform: translateX(-50%) translateY(100px);
  }
  100% {
    opacity: 1;
    transform: translateX(-50%) translateY(0);
  }
}
```

**Comment by tetsuya2223** [comment]
一旦現状のコードをコミットしておきました！
392cde82cfbb003ad4710bf3f40d7b06d884c75d

**Comment by tetsuya2223** [comment]
useEffectで`closeToast()`を呼び出さない場合の`isVisible`のlog

・初期値はfalse
・「保存」ボタン押下時にtrueに
・その後falseにはならず
<img width="1127" alt="Image" src="https://github.com/user-attachments/assets/77652d2c-7e4a-487d-b38e-87b8ec1cbda4" />

**Comment by tetsuya2223** [comment]
useEffectで`closeToast`を呼び出した場合、うまくいく。

<img width="1205" alt="Image" src="https://github.com/user-attachments/assets/e4876654-28ba-4958-b417-66a6bb216c8d" />

**Comment by tetsuya2223** [comment]
アニメーションがうまく動作しなかった要因
```css
.toast {
    transform: translateX(-50%) translateY(100px);
}
````
余計な`translateY(100px`があったため。
toastが下から出てくる⇒デフォルトの位置（translateY(100px)画面下部）に戻る⇒アンマウント前に上に戻ってから下に下がって消える。
と言う挙動になってしまった。
